sudo: false
language: minimal
git:
  submodules: false  # whether to recursively clone submodules

cache:
  directories:
    - $HOME/.stack

matrix:
  include:
  - env: STACK_YAML=stack-8.4.yaml
  - env: STACK_YAML=stack-8.6.yaml

before_install:
# Download and unpack the stack executable
- mkdir -p $HOME/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
 - travis_wait stack --no-terminal setup
 # Build packages
 - stack build --ghc-options="-Wall -Werror"
 # Run tests
 - stack test --ghc-options="-Wall -Werror"
 # It would be good to build documentation, but it currently seems to take too long.
 - stack haddock