name: Build and Test
on:
  - push
  - pull_request
jobs:
  linux:
    name: Testing ${{ matrix.os }} GHC-${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.allow-failure }}
    strategy:
      matrix:
        os: [ubuntu-24.04]
        # See doc/dev.md for GHC version support policy
        ghc: [9.10.1, 9.8.1, 9.6.1, 9.4.5, 9.2.2, 9.0.2, 8.10.7, 8.8.4, 8.6.5]
        allow-failure: [false]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        id: setup-haskell
        with:
          ghc-version: ${{ matrix.ghc }}
      - uses: actions/cache/restore@v4
        name: Restore cabal store cache
        id: cache
        env:
          # NB: Each `matrix.os` (e.g., `ubuntu-22.04-arm`) uniquely determines
          # a `runner.arch` (e.g., ARM64), so there is no need to include the
          # latter as part of the cache key
          key: cabal-${{ matrix.os }}-ghc${{ matrix.ghc }}
        with:
          path: |
            ${{ steps.setup-haskell.outputs.cabal-store }}
            dist-newstyle
          key: |
            ${{ env.key }}-${{ github.ref }}
          restore-keys: |
            ${{ env.key }}-
      - name: Cabal update
        shell: bash
        run: cabal update
      - name: Cabal check
        shell: bash
        run: cabal check
      - name: Configure
        shell: bash
        # See doc/dev.md for development practices around warnings.
        run: cabal configure --enable-tests --ghc-options='-Werror=compat -Werror=default'
      - name: Build
        shell: bash
        run: cabal build
      - name: Test
        shell: bash
        run: cabal test
      - name: Documentation
        shell: bash
        run: cabal haddock
      - uses: actions/cache/save@v4
        name: Save cabal store cache
        if: always()
        with:
          path: |
            ${{ steps.setup-haskell.outputs.cabal-store }}
            dist-newstyle
          key: ${{ steps.cache.outputs.cache-primary-key }}
      - name: Check Cabal/GHC compatibility
        uses: langston-barrett/.github/actions/cabal-ghc-compat@7a8e0a0c28851afefc845bfca22143c9ba06722b
        with:
          ghc: ${{ matrix.ghc }}
          token: ${{ secrets.GITHUB_TOKEN }}